package guvnor.feature.enumeration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EnumFact implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(2)
    private java.lang.Integer fieldInteger1;

    @org.kie.api.definition.type.Position(3)
    private java.lang.Integer fieldInteger2;

    @org.kie.api.definition.type.Position(0)
    private java.lang.String fieldString1;

    @org.kie.api.definition.type.Position(1)
    private java.lang.String fieldString2;

    @org.kie.api.definition.type.Position(4)
    private java.lang.Integer fieldInteger3;

    @org.kie.api.definition.type.Position(5)
    private java.lang.String fieldString3;

    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer fieldInteger4;

    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String fieldString4;

    public java.lang.Integer getFieldInteger1() {
        return this.fieldInteger1;
    }
    
    public void setFieldInteger1(java.lang.Integer fieldInteger1) {
        this.fieldInteger1 = fieldInteger1;
    }

    public java.lang.Integer getFieldInteger2() {
        return this.fieldInteger2;
    }
    
    public void setFieldInteger2(java.lang.Integer fieldInteger2) {
        this.fieldInteger2 = fieldInteger2;
    }

    public java.lang.String getFieldString1() {
        return this.fieldString1;
    }
    
    public void setFieldString1(java.lang.String fieldString1) {
        this.fieldString1 = fieldString1;
    }

    public java.lang.String getFieldString2() {
        return this.fieldString2;
    }
    
    public void setFieldString2(java.lang.String fieldString2) {
        this.fieldString2 = fieldString2;
    }

    public java.lang.Integer getFieldInteger3() {
        return this.fieldInteger3;
    }

    public void setFieldInteger3(java.lang.Integer fieldInteger3) {
        this.fieldInteger3 = fieldInteger3;
    }

    public java.lang.String getFieldString3() {
        return this.fieldString3;
    }

    public void setFieldString3(java.lang.String fieldString3) {
        this.fieldString3 = fieldString3;
    }

    public java.lang.Integer getFieldInteger4() {
        return this.fieldInteger4;
    }

    public void setFieldInteger4(java.lang.Integer fieldInteger4) {
        this.fieldInteger4 = fieldInteger4;
    }

    public java.lang.String getFieldString4() {
        return this.fieldString4;
    }

    public void setFieldString4(java.lang.String fieldString4) {
        this.fieldString4 = fieldString4;
    }

    public EnumFact() {
    }

    public EnumFact(java.lang.String fieldString1,
            java.lang.String fieldString2, java.lang.Integer fieldInteger1,
            java.lang.Integer fieldInteger2, java.lang.Integer fieldInteger3,
            java.lang.String fieldString3, java.lang.Integer fieldInteger4,
            java.lang.String fieldString4) {
        this.fieldString1 = fieldString1;
        this.fieldString2 = fieldString2;
        this.fieldInteger1 = fieldInteger1;
        this.fieldInteger2 = fieldInteger2;
        this.fieldInteger3 = fieldInteger3;
        this.fieldString3 = fieldString3;
        this.fieldInteger4 = fieldInteger4;
        this.fieldString4 = fieldString4;
    }

}
