package guvnor.bugs.boundvar;

import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
// $HASH(cc3383bee505ff38ec0256b41ef9ec3d) (added manually)
@XmlType(namespace = "guvnor.bugs.boundvar")
public class Fact2  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private java.lang.Integer field_b;
    
    private guvnor.bugs.boundvar.Fact1 fielda;
    
    private java.lang.String s_field;

    public Fact2() {
    }

    public Fact2(java.lang.Integer field_b, guvnor.bugs.boundvar.Fact1 fielda, java.lang.String s_field) {
        this.field_b = field_b;
        this.fielda = fielda;
        this.s_field = s_field;
    }


    
    public java.lang.Integer getField_b() {
        return this.field_b;
    }

    public void setField_b(  java.lang.Integer field_b ) {
        this.field_b = field_b;
    }
    
    public guvnor.bugs.boundvar.Fact1 getFielda() {
        return this.fielda;
    }

    public void setFielda(  guvnor.bugs.boundvar.Fact1 fielda ) {
        this.fielda = fielda;
    }
    
    public java.lang.String getS_field() {
        return this.s_field;
    }

    public void setS_field(  java.lang.String s_field ) {
        this.s_field = s_field;
    }
}