package guvnor.bugs.boundvar;

import javax.xml.bind.annotation.XmlType;

/**
 * This class was automatically generated by the data modeler tool.
 */
// $HASH(d6818a6dbc04d05c7be5cb569372fb2d) (added manually)
@XmlType(namespace = "guvnor.bugs.boundvar")
public class Fact1  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private Integer field2;
    
    private String field1;

    public Fact1() {

    }
    
    public Integer getField2() {
        return this.field2;
    }

    public void setField2(  Integer field2 ) {
        this.field2 = field2;
    }
    
    public String getField1() {
        return this.field1;
    }

    public void setField1(  String field1 ) {
        this.field1 = field1;
    }




}