package guvnor.feature.datamodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ClassWithAllPrimitives implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(1)
   private byte byte1;

   @org.kie.api.definition.type.Position(2)
   private char char1;

   @org.kie.api.definition.type.Position(3)
   private double double1;

   @org.kie.api.definition.type.Position(4)
   private float float1;

   @org.kie.api.definition.type.Position(5)
   private int int1;

   @org.kie.api.definition.type.Position(6)
   private long long1;

   @org.kie.api.definition.type.Position(7)
   private short short1;

   @org.kie.api.definition.type.Position(0)
   private boolean boolean1;

   public byte getByte1()
   {
      return this.byte1;
   }

   public void setByte1(byte byte1)
   {
      this.byte1 = byte1;
   }

   public char getChar1()
   {
      return this.char1;
   }

   public void setChar1(char char1)
   {
      this.char1 = char1;
   }

   public double getDouble1()
   {
      return this.double1;
   }

   public void setDouble1(double double1)
   {
      this.double1 = double1;
   }

   public float getFloat1()
   {
      return this.float1;
   }

   public void setFloat1(float float1)
   {
      this.float1 = float1;
   }

   public int getInt1()
   {
      return this.int1;
   }

   public void setInt1(int int1)
   {
      this.int1 = int1;
   }

   public long getLong1()
   {
      return this.long1;
   }

   public void setLong1(long long1)
   {
      this.long1 = long1;
   }

   public short getShort1()
   {
      return this.short1;
   }

   public void setShort1(short short1)
   {
      this.short1 = short1;
   }

   public boolean isBoolean1()
   {
      return this.boolean1;
   }

   public void setBoolean1(boolean boolean1)
   {
      this.boolean1 = boolean1;
   }

   public ClassWithAllPrimitives()
   {
   }

   public ClassWithAllPrimitives(boolean boolean1, byte byte1, char char1,
         double double1, float float1, int int1, long long1, short short1)
   {
      this.boolean1 = boolean1;
      this.byte1 = byte1;
      this.char1 = char1;
      this.double1 = double1;
      this.float1 = float1;
      this.int1 = int1;
      this.long1 = long1;
      this.short1 = short1;
   }
}
