package guvnor.feature.datamodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order153 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Order153() {
    }

}