package guvnor.feature.standalone;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OtherFact implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OtherFact() {
    }

}