package guvnor.feature.standalone;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StandaloneFact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(0)
   private java.lang.String name;
   @org.kie.api.definition.type.Position(1)
   private java.lang.String city;

   @org.kie.api.definition.type.Position(value = 2)
   private java.lang.Integer value;

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.Integer getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Integer value)
   {
      this.value = value;
   }

   public StandaloneFact()
   {
   }

   public StandaloneFact(java.lang.String name, java.lang.String city,
         java.lang.Integer value)
   {
      this.name = name;
      this.city = city;
      this.value = value;
   }

}