package guvnor.bugs.dsl_enum;

/**
 * This class was automatically generated by the data modeler tool.
 */
// $HASH(a2c239f25d60a234005dbe0d3e800e8f) (added manually)
public class Vehicle implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private String engineType;
    private String fuelType;

    public Vehicle() {
    }

    public String getEngineType() {
        return this.engineType;
    }

    public void setEngineType(String engineType) {
        this.engineType = engineType;
    }

    public String getFuelType() {
        return this.fuelType;
    }

    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }
}